/*
  LIAMCONOMIST ARTICLE FILE
  ========================
  To publish a new story, copy one article object below, paste it at the TOP of
  the array, and replace its fields. Keep every id unique and use only lowercase
  letters, numbers and hyphens in it. Set `featured: true` on only one story.

  Photos go in the /assets folder. Use a path such as "assets/liam-cooking.jpg".
  If you do not have a photo yet, set image to "" and the article will work
  without one.
*/

window.LIAM_ARTICLES = [
  {
    id: "takeaway-policy",
    featured: true,
    category: "Domestic policy",
    title: "Liam signals historic shift in housing policy",
    summary: "Years of literal 'Where in the world are you?' are rapidly fading as Liam's time spent in a single city peaked at a whopping four months. Insiders describe the move as pragmatic, courageous and mostly prompted by Liam framing lifestyle stability as a challenge.",
    author: "Chief Liamconomist Editor",
    date: "2026-07-04",
    location: "Casa Brunswick",
    readTime: "4 min read",
    image: "assets/cost-of-living-collage.png",
    imageAlt: "A playful editorial collage of a house, a receipt and a hand holding a coin",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "I challenge myself to stay in the same city for 12 months.",
    body: [
      "On a Himalayan peak, in a 10-day silent retreat, a remote farming town in China, swimming under the Eiffel Tower, stacking a rock cairn in Utah, hitchhiking up Eastern Australia. For years, the only way Liam's family and friends could trace his location was by pinging him a codephrase - 'Where in the world are you?'. They learned pretty quickly to brace themselves for a random response.",
      "As of June 2026, a metric quietly ticked over a new milestone. Liam's coordinates, previously erratic, hadn't changed for four months. Markets moved immediately. The shift should not be mistaken for an error - Liam did not forget how to get to the airport nor did he lose his bank card. Instead, it reflects Liam's new housing policy.",
      "Famous for his pro-adventure policies, this comes a shock to many. Yet only the closest analysts would be familiar with his lesser known policies which express strong support for the challenge sector. It's with this philosophy that Liam adopted his new housing policy - imbuing challenge into what most might think as routine - staying put.",
      "For the wild nomad, Brunswick presents new challenges. Ordering a magic without knowing what it is. Trying to remember what food is in his fridge when he's at the shops. Navigating Barkly Square and retaining sanity.",
      "As of now, it is still unclear what the policy seeks to achieve but it guarantees one thing - that we'll discover a new challenge at the end of the 12 months."
    ]
  },
  {
    id: "morning-routine",
    featured: false,
    category: "decisions",
    title: "Liam’s morning strategy enters a bold new phase",
    summary: "Princes Park is still reeling from witnessing an hour of burpees.",
    author: "Ethanol Sharpie",
    date: "2026-06-28",
    location: "Carlton",
    readTime: "3 min read",
    image: "assets/morning-routine-poster.jpg",
    imageAlt: "Video still of Liam performing burpees during a training session at Princes Park",
    imageCaption: "Video still: Liamconomist",
    video: "assets/morning-routine.mp4",
    videoPoster: "assets/morning-routine-poster.jpg",
    videoAlt: "Liam performing burpees during a training session at Princes Park",
    videoCaption: "Video: Liamconomist",
    pullQuote: "Thus birthed the idea of meeting up at Princes Park once a week and training burpees across the footy oval.",
    body: [
      "Liam has unveiled a novel exercise programme that consists purely of doing burpees.",
      "The plan began with a pledge to do burpees for one mile. Close consultation with exercise scientists revealed a slightly worrying statistic - at least a thousand burpees. Did he and his team have the strength and stamina?",
      "Initial piloting of the strategy has shown promise: one hour of burpees covers around 400 metres. Additionally, the camaraderie demonstrated in training is unparalleled - free beans for when times get inevitably tough when the burpee mile arrives. He is trying to convince as many parties as possible to join him once a week, in the cold, damp, public grass.",
      "Observers remain optimistic that a burpee mile can be performed before end of Q3 2026."
    ]
  },
  {
    id: "bone-broth",
    featured: false,
    category: "Charts",
    title: "Is goat broth overtaking beef broth?",
    summary: "The stats will shape Liam's weekly trip to Queen Victoria Market.",
    author: "K-Dog",
    date: "2026-06-30",
    location: "Casa Brunswick",
    readTime: "3 min read",
    image: "assets/broth_attention.png",
    pullQuote: "Goat bones may be the contrarian asset of the winter soup cycle.",
    body: [
      "Casa Brunswick has been gripped by a question of unusual economic and culinary significance: is goat broth overtaking beef broth?",
      "A shift toward goat bones would alter Liam’s weekly Queen Victoria Market strategy, forcing a reassessment of butcher reliability, freezer capacity and the long-run yield of collagen per dollar. Beef, long considered the blue-chip broth asset, offers familiarity, heft and a certain Sunday-roast respectability. Goat, by contrast, is leaner, stranger and possibly undervalued by the broader soup market.",
      "Analysts (Liam, Liam and Liam) are divided. Some argue that goat bones represent a contrarian buying opportunity: cheap, flavourful and still underhyped. Others warn that the goat thesis depends heavily on patience, skimming discipline and a tolerance for aromas that may test household diplomacy.",
      "For now, Liam is expected to maintain a diversified bone portfolio. But with winter demand rising and the Brunswick liquidity environment cooling, goat broth’s market share may yet climb. The next trip to Queen Victoria Market could decide whether this is a temporary simmer or the start of a structural broth rotation."
    ]
  },
  {
    id: "yoghurt-ranking",
    featured: false,
    category: "Analysis",
    title: "Sources confirm Liam has a new favourite yoghurt brand",
    summary: "Aldi’s Lyttos has displaced a long-serving incumbent after Liam’s yoghurt demand increased tenfold.",
    author: "Pumpkeen",
    date: "2026-06-21",
    location: "Casa Brunswick",
    readTime: "2 min read",
    image: "assets/yoghurt-ranking.png",
    imageAlt: "An editorial illustration showing an affordable yoghurt tub overtaking a premium competitor at breakfast",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "Jalna is a good yoghurt. But I can't justify the price with the quantities I consume.",
    body: [
      "A loud revolution has taken place in Liam’s kitchen cupboard. Lyttos, Aldi's Greek-style yoghurt, is now the first choice for breakfast, displacing Jalna after years of dependable service.",
      "Its rise reflects a combination of function, price and bowel movement requirements. For years, yoghurt played a supporting role to eggs and toast. With Liam's recent consumption shifting to include creatine and psyllium husk, demand for a food with more suitable texture grew 140%.",
      "Eggs briefly retained their position through familiarity and protein content. But yoghurt offered that indispensable powder-carrying capability. It wasn't long before yoghurt surpassed eggs as the breakfast of choice.",
      "Price secured the regime change. Lyttos promised the required volume without placing undue pressure on the household breakfast budget.",
      "The former favourite is expected to remain in service, on occasions when Liam does grocery shopping elsewhere."
    ]
  },

  {
    id: "haircut-debate",
    featured: false,
    category: "Personal affairs",
    title: "The great haircut debate reaches its decisive phase",
    summary: "Liam agrees that his hair is getting long, while the next cut remains elusive.",
    author: "Charles Leclerc",
    date: "2026-06-14",
    location: "Paris",
    readTime: "2 min read",
    image: "assets/haircut.jpeg",
    imageAlt: "",
    imageCaption: "Liam's hair beginning to take a life of it's own.",
    pullQuote: "I’ll book it this week, said Liam, defining neither ‘book’ nor ‘this week’.",
    body: [
      "The evidence has been accumulating for days. The fringe has entered Liam’s field of vision and the sides are no longer responding to diplomacy.",
      "Liam accepts the broad case for reform. Yet whether a haircut is required remains subject to consultation. Some enjoy his longer curls, while others prefer a sleeker head.",
      "Analysts expect the matter to be resolved only when an unexpectedly free afternoon coincides with an available barber."
    ]
  },
  {
    id: "coffee-doctrine",
    featured: false,
    category: "Daily briefing",
    title: "Could one more coffee fix Liam’s morning?",
    summary: "A second French press promises productivity, clarity and the possibility of breakfast.",
    author: "Flatte White",
    date: "2026-06-07",
    location: "Kitchen",
    readTime: "3 min read",
    image: "assets/coffee.jpg",
    imageAlt: "",
    imageCaption: "Illustration: Cristina Spanò",
    pullQuote: "The first coffee established stability. The second may deliver growth.",
    body: [
      "By 9.15am the first coffee had performed admirably. Liam was awake, conversational and aware that it was Tuesday.",
      "The case for a second cup rests on more ambitious goals: creating a new CSGO trading bot and moving his pants from one end of the room to the other.",
      "Critics warn of diminishing returns. Liam has taken their concerns under advisement while switching on the machine."
    ]
  },
  // {
  //   id: "missing-food",
  //   featured: false,
  //   category: "analysis",
  //   title: "The Liam Effect: fridges tremble in his presence",
  //   summary: "Family members have reported a 78% decrease in food disappearance since he got his own fridge in Brunswick.",
  //   author: "Eedee",
  //   date: "2026-06-14",
  //   location: "Geelong",
  //   readTime: "2 min read",
  //   image: "assets/fridge.png",
  //   imageAlt: "",
  //   imageCaption: "",
  //   pullQuote: "The Liam Effect has not disappeared. It has merely been given its own fridge.",
  //   body: [
  //   "His lifestyle could have been largely described as nomadic, his path an anchor to which the Liam Effect could be studied. For years, Liam's visits to a family member's house followed a familiar pattern: arrive warmly, greet with too much energy, inspect the fridge, and leave behind a household light on their week's groceries.",
  //   "New emerging data suggests the era of food disappearance may be ending. After months of living in his own Brunswick home, Liam's family have reported a 78% decrease in missing food. The decline has been attributed not to a change in appetite, ideology or moral philosophy, but to a more powerful structural reform.",
  //   "Still, analysts warn against complacency. The long-term question is whether the family’s food security will hold during visits, holidays and periods of Brunswick understocking. For now, however, the data is clear: the Liam effect has been contained, not eliminated."
  //   ]
  // },
  {
    id: "czech-base",
    featured: false,
    category: "security",
    title: "Ordinary man infiltrates abandoned DayZ military base",
    summary: "Liam entered the Czech complex alone, climbed its towers and continued filming after nearby gunshots raised questions about his threat-assessment procedures.",
    author: "Liamconomist Correspondent - Europe",
    date: "2026-06-30",
    location: "Undisclosed, Czech Republic",
    readTime: "3 min read",
    image: "assets/czech-base.png",
    imageAlt: "An editorial illustration of a lone vlogger climbing a watchtower in an abandoned Czech military base",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "This location always had shit loot.",
    body: [
      "When asked 'What did you get up to on the holidays?', of course Liam has a weird thing to say. The Australian man broke into an abandoned military base somewhere in the Czech Republic, guided by geo-coordinates he found on a subreddit, conducting the operation alone and with no apparent support beyond a camera used to record his vlog.",
      "The complex was of particular strategic interest because it inspired a military base in DayZ, a video game Liam and Hugo played extensively during their teenage years. What began as tourism therefore developed into a live comparison between digital geography and a real facility whose security arrangements appeared largely theoretical.",
      "Once inside, Liam roamed freely through the decaying compound and climbed several towers to survey the grounds. His enthusiasm increased as more familiar structures emerged. The absence of companions, functioning infrastructure or obvious permission did little to weaken morale.",
      "The expedition acquired a chaotic dimension when gunshots were heard nearby. Conventional threat assessments might have recommended an orderly withdrawal. Instead, Liam continued deeper into the base, apparently treating the noise as further evidence that the visit was becoming interesting.",
      "Friends reviewing the footage are left bewildered by Liam’s commitment to immersive research while openly questioning his sanity. The expedition has since become a useful case study in the limits of curiosity, personal risk assessment and travelling without adult supervision."
    ]
  },
  {
    id: "stripper-pants",
    featured: false,
    category: "Culture",
    title: "The rise of the stripper pants",
    summary: "A pair of vintage Nike tearaways has become Liam’s most controversial wardrobe holding.",
    author: "Eedee",
    date: "2026-06-30",
    location: "Melboner",
    readTime: "2 min read",
    image: "assets/stripper_pants.png",
    pullQuote: "Liam, why do you own stripper pants?",
    body: [
      "Few analysts expected that Liam's most robust wardrobe asset to be a pair of vintage Nike tearaway pants. The garment dates back to the 90s and is equipped with buttons running dramatically down each side. For, as one might guess, ease of stripping.",
      "The pants entered Liam’s possession through an unusually informal supply chain. They were given to him by his girlfriend, who had reportedly pilfered them from her uncle’s old wardrobe. Since then, the garment has moved from inherited curiosity to daily infrastructure. Liam wears them frequently, confidently and, according to relatives, with insufficient regard for the social implications of side-release trousers.",
      "There is no doubt that the construction quality of the vintage pants meets the demanding needs of Liam's rough-and-tumble approach to life. He will wear any item of clothing to work, exercise, and church if he has to. In an age of disposable and fast-fashion, Liam has actually chosen durability, timelessness and sustainability. It just so happens to bring with it a slight aura of public indecency risk."
    ]
  },
  {
    id: "skin-removal",
    featured: false,
    category: "opinion",
    title: "A revolutionary, low-cost solution to baby feeding",
    summary: "It upholds Liam's engineering philosophy - simple solutions are the best.",
    author: "Eedee",
    date: "2026-07-02",
    location: "Brisbane",
    readTime: "2 min read",
    image: "assets/pear.png",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "Innovation often begins where cutlery ends.",
    body: [
      "The early-20s man is rarely considered the core demographic for infant-feeding innovation. Nevertheless, Liam has once again demonstrated that engineering breakthroughs often emerge from people with no formal mandate to produce them.",
      "Liam was feeding his baby nephew on the sofa. He placed a piece of pear in the baby’s mouth, when the baby’s mother suggested removing the pear skin to make the fruit easier to chew. Many caregivers might have reached for a knife to slice the skin off, or perhaps a plate or napkin to assist in peeling the skin off.",
      "Liam's engineering training kicked into gear. Good design is obvious, but great design is transparent. Making use of the resources at hand, Liam retrieved the pear from the baby's mouth, bit off the skin with his own teeth, and returned the modified fruit to its original destination.",
      "Parenting experts may hesitate to endorse the method. But as a case study in low-cost process optimisation, it was undeniably Liam."
    ]
  },
  {
    id: "plane-jumping",
    featured: false,
    category: "events",
    title: "Liam's gaslighting conviction",
    summary: "How the man convinced his own mother and best mate to jump out of a plane.",
    author: "Lucyfer Bohaner",
    date: "2026-06-21",
    location: "Torquay Airport",
    readTime: "2 min read",
    image: "assets/parachute.jpg",
    imageCaption: "Pictured: Liam's mother at great heights",
    pullQuote: "You ever get high with your child?",
    body: [
      "Torquay Airport is now the site of a major behavioural case study after Liam successfully convinced his own mother and best mate to jump out of a plane.",
      "Liam's correspondants have declined to respond to questions on how the negotiations unfolded. However, behvaioural experts surprisingly agree on a consensus: gaslighting.",
      "No evidence suggested any discussion took place. In fact, document reviews reveal that barely 72 hours separated the first verbal suggestion from the eventual ousting from the plane. In that timeframe, Liam merely made contact to co-ordinate setting up camp in his mother's backyard, a level of contact experts note as significantly lighter than usual for the mother and son.",
      "As for Po's involvement, the guy had even less of a fighting chance. He didn't know what was happening until he woke up strapped to another man, 15,000 feet in the air."
    ]
  },
  {
    id: "slacklining",
    featured: false,
    category: "decisions",
    title: "Slacklining is too easy",
    summary: "Do it holding two bicycles.",
    author: "Ethanol Sharpie",
    date: "2026-06-07",
    location: "Carlton",
    readTime: "4 min read",
    image: "assets/slackline.jpg",
    imageCaption: "Pictured: Experimental slacklining",
    pullQuote: "What is slacklining? - the Urgent Care Nurse",
    body: [
      "Liam has unveiled a bold attempt to solve slacklining’s most persistent problem: that, in its conventional form, it had become far too easy for him.",
      "Rather than seek a narrower line or a more difficult route, Liam introduced additional equipment. He stepped onto the slackline carrying two bicycles, transforming a casual balancing exercise into a complicated test of weight distribution, upper-body strength and personal judgment.",
      "Like most newly signed treaties in geopolitics, they don't always integrate smoothly. Liam lost his balance and fell, becoming entangled with one of the bicycles. Its gear punctured him, bringing the experiment to an abrupt end.",
      "The resulting injury required a visit to urgent care, where Liam received several stitches. Medical professionals repaired the immediate damage, though broader clarification regarding the activity was not reached and was expected to persist in their minds long after their shifts were over.",
      "The episode has not discouraged nor invalidated experimental slacklining altogether. Insiders say that Liam is preparing to sign a new decree, one granting the use of baked goods."
    ]
  },
  {
    id: "24h-hike",
    featured: false,
    category: "opinion",
    title: "Walking for 24 hours straight just because",
    summary: "How does he keep convincing us to join him?",
    author: "Ankle Oatmilk",
    date: "2026-06-14",
    location: "Great Ocean Walk",
    readTime: "4 min read",
    image: "assets/hike.jpeg",
    imageCaption: "Pictured: Liam and his lured recruits",
    pullQuote: "Are we there yet?",
    body: [
      "There are easier invitations to accept than walking continuously for 24 hours. For example, dinner, a short stroll and almost every recognised form of leisure. Yet Liam has now embarked on his endurance hike three times, recruiting a larger group for each attempt.",
      "The obvious explanation is camaraderie. Shared exhaustion has a peculiar ability to accelerate friendship. After enough kilometres, ordinary conversation gives way to a special type of purgatory made especially for our snowflake generation.",
      "Other analysts propose simple insanity as a competing theory. Participants know the hike will involve aching feet, limited sleep and prolonged exposure to Liam’s motivational philosophy. They join anyway. This suggests either a serious failure of risk assessment or a remarkable degree of trust.",
      "Then there is the meme. Completing the walk provides membership to a highly specific club, where members can finally have conversations that go like this: 'I walked for 24 hours straight.' 'Why?' 'Just cos.'",
      "The formula combines three things Liam loves: doing something unnecessarily hard, doing it alongside his friends and consuming heroic quantities of food. His recruits may arrive for different reasons, but they leave with the same conclusion: against their better judgment, they will probably return next year."
  ]
  },
  {
    id: "cypriot-iceskate",
    featured: false,
    category: "personal affairs",
    title: "Did joining the Cypriot figure-skating team make Liam a communist?",
    summary: "Ice-skating and communism have more in common than you think.",
    author: "Poetry-Chen Liu",
    date: "2026-06-28",
    location: "Cyprus",
    readTime: "4 min read",
    image: "assets/skater.png",
    imageAlt: "An editorial illustration of a young figure skater performing on a tiny ice rink surrounded by a Mediterranean landscape",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "Both systems demand collective discipline, coordinated clothing and absolute faith that nobody will fall.",
    body: [
      "In his youth, Liam was a member of Cyprus’s national figure-skating team. This is among the most remarkable facts about his childhood, partly because Cyprus is a Mediterranean island better known for beaches than frozen sporting infrastructure, but mainly because this is the guy that does Iron Mans for fun. Almost nobody believes him when he mentions it.",
      "However, in the past several years, critics have begun to draw correlations between Liam's figure-skating and certain ideological tendencies. A strong advocate for self-expression, Liam learned through figure-skating that self-expression wins on the ice and should be pursued at all costs, provided that it has been rehearsed for years and approved by a committee.",
      "Moreoever, another pillar of his philosophy states that in life, luck and winning falls in the hands of the powers above. Figure-skaters win through a collective judgement by panels, codes, scores and invisible standards of ideological purity out of the individual's control. Sound familiar?",
      "The two worlds also share an unusual enthusiasm for revolution. Skaters complete as many as possible, while political theorists generally recommend beginning with one, but won't hesitate to spark more. Both traditions favour coordinated outfits, stern officials and dramatic displays set to orchestral music.",
      "There is no firm evidence that joining the Cypriot team made Liam a communist. It did, however, teach him that improbable institutions can survive through discipline, shared resources and the refusal of outsiders to believe they exist. At seven years old, Liam had already learned to defend both his balance and an extraordinary personal history."
      ]
  },
  {
    id: "basil-ramen",
    featured: false,
    category: "opinion",
    title: "Basil in instant noodles: cultural appropriation or smooth-brained?",
    summary: "The debate goes a bit deeper than ramen.",
    author: "Poetry-Chen Liu",
    date: "2026-06-21",
    location: "Carlton",
    readTime: "4 min read",
    image: "assets/basil.png",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "The central question is not whether Liam respected tradition, but whether he understood flavour.",
    body: [
      "Few issues in modern public life are as needlessly combustible as authenticity in food. Yet even by that standard, Liam’s decision to put basil in instant ramen produced a disproportionate diplomatic incident. To Liam, the herb appears to have been merely available. To an Asian friend present at the scene, it represented something closer to culinary vandalism.",
      "Two explanations compete. The first is ideological: that Liam intervened in a dish with his own improvisational logic, flattening context and tradition into a vague personal experiment. And, his ethnicity - white out of his control - renders any curiousity he has as white entitlement. The second is more mundane and, perhaps for Liam, more credible: that he simply saw noodles, saw basil, and failed to apply any filtering mechanism between impulse and action.",
      "The evidence tilts toward incompetence rather than imperialism. Instant noodles are not sacred museum objects, and basil is not wholly alien to Asian cuisines. The deeper offence lies elsewhere. Liam merely committed a smaller, sadder act of kitchen reasoning: the assumption that any green leaf improves any hot bowl.",
      "His friend’s disgust was therefore understandable."
    ]
  },  
  {
    id: "chicken-index",
    featured: false,
    category: "data",
    title: "The price of a whole chicken now reveals more than GDP ever could",
    summary: "Found in many Australian pantries, the humble Whole Chicken is Liamconomist's preferred proxy of the Aussie consumer's buying power.",
    author: "Colonel Sanders",
    date: "2026-07-02",
    location: "Carlton",
    readTime: "4 min read",
    image: "assets/chicken.png",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "GDP describes the economy. A whole chicken reveals whether anybody can still afford dinner.",
    body: [
      "Economists traditionally measure household prosperity through wages, inflation and gross domestic product. These indicators are comprehensive, respected and almost entirely useless when standing hungry in a supermarket aisle.",
      "The Liamconomist Whole Chicken Index offers a more practical alternative. A chicken is widely available, broadly comparable between shops and capable of feeding several people - or one sufficiently motivated Liam. Its price captures changes in farming, transport, refrigeration and the increasingly ambitious expectations placed upon the weekly grocery budget.",
      "The methodology is deliberately rigorous. Researchers observe the shelf price of an uncooked whole chicken. Results are then adjusted for bird size, seasoning and whether dinner guests are likely to request seconds.",
      "A rising index signals declining purchasing power. Consumers may respond by reducing portion sizes, substituting cheaper proteins or quietly deciding that the side dishes constitute a complete meal. A falling index suggests improved conditions and the possible return of midweek abundance.",
      "The measure has limitations. Chickens vary in weight, quality and aerodynamic potential. Yet unlike GDP, the index answers a question households confront directly: what can tonight’s budget place on the table? Until conventional statistics become edible, the whole chicken remains Liamconomist’s preferred economic unit."
    ]
  }, 
  {
    id: "trampoline-boat",
    featured: false,
    category: "opinion",
    title: "What the trampoline boat reveals about second-hand marketplaces",
    summary: "The consensus looks buoyant. Make capitalism walk the plank!",
    author: "Lucyfer Bohaner",
    date: "2026-06-14",
    location: "Moorabool",
    readTime: "4 min read",
    image: "assets/trampoline.jpeg",
    imageCaption: "Image: Gen-Z can't afford to buy houses, may as well buy a trampoline boat.",
    pullQuote: "The property market is ludicrous; the trampoline-boat market is much more sensible.",
    body: [  
      "Facebook Marketplace is generally understood as a monument to small-scale capitalism: strangers exchange unwanted objects for money, negotiate aggressively and disappear before anybody can request a refund. Liam saw something more promising—a trampoline boat.",
      "The vessel was too ambitious for one buyer and too ridiculous to ignore. Liam therefore assembled a coalition of friends, persuading each member to contribute money towards its purchase. Individual hesitation was overcome by the prospect of shared ownership and the important question of whether a trampoline could remain entertaining while floating.",
      "Acquisition was only the beginning. The boat required repairs before it could sail, turning its new owners into an improvised shipyard workforce. Money, tools and labour were pooled. Responsibility became collective, although Liam’s enthusiasm remained the project’s primary source of momentum.",
      "The repaired vessel was eventually launched on the Moorabool. The experiment worked exactly as promised: its passengers could bounce, abandon the deck for a swim and climb aboard again. Against considerable odds, the trampoline boat was perfect.",
      "The episode offers a lesson for second-hand markets. Capitalism may place unusual assets online, but friendship can remove them from individual ownership and convert them into public infrastructure for a very small public. The revolution may not begin in a factory. It may begin with a suspicious Facebook listing and several friends willing to chip in."
    ]
  },
  {
    id: "3-nipples",
    featured: false,
    category: "charts",
    title: "How many nipples is too many nipples?",
    summary: "Tom Cashman's curve places Liam at the bottom of the excitement chart.",
    author: "Lucyfer Bohaner",
    date: "2026-06-07",
    location: "Melboner",
    readTime: "3 min read",
    image: "assets/nipples.jpeg",
    imageCaption: "Graph: Tom Cashman",
    pullQuote: "Three is too many for normality and not enough for spectacle.",
    body: [
        "Most anatomical models assume that two nipples represent a stable equilibrium. Liam, who has three, offers economists and amateur statisticians an opportunity to examine what happens when the market receives unexpected additional supply.",
        "A graph presented during a standup set by comedian Tom Cashman proposes a bleak initial answer. Its curve reaches its lowest point at three nipples, suggesting that one additional nipple produces the maximum possible disruption without delivering sufficient novelty in return.",
        "The logic is cruel but internally consistent. Three abandons conventional symmetry while remaining close enough to the standard arrangement to invite comparison. It is unusual, yet not so unusual that observers stop judging and begin asking important research questions.",
        "Beyond three, however, the curve begins to rise. Larger quantities apparently benefit from a curiosity premium. What looked like an anatomical irregularity becomes a collection, a phenomenon or perhaps evidence of an entirely different operating model.",
        "Liam therefore occupies the graph’s least advantageous position: the exact trough between normality and spectacle. It represents something broader; a warning about marginal supply. In nipples, as in economics, one additional unit can be more destabilising than several."
      ]
  },
  {
    id: "spies",
    featured: false,
    category: "editorial",
    title: "The interns who came in from the cold",
    summary: "A spy network staffed by the world’s youngest and brightest.",
    author: "Kris Kristensen",
    date: "2026-07-04",
    location: "Geelong",
    readTime: "7 min read",
    image: "assets/spies2.jpg",
    imageCaption: "Image: They don't look anything like James Bond.",
    pullQuote: "What if the 'funemployment' is not actually 'fun' at all?",
    body: [
      "There are plots that arrive wearing dark glasses, and plots that arrive wearing lanyards. This one, if the breathless memos are to be believed, came with a graduate-development handbook, a risk-assessment form and a cohort photo taken in the guise of a house-warming party.",
      "The allegation, improbable but not entirely without modern charm, is that an international network of military-grade graduate trainees has been dispatched across campuses, start-ups and research facilities to do what spies used to do with dead drops and raincoats. They attend seminars, exchange business cards, linger at receptions and appear, with unnerving regularity, wherever a defence contract, a sensor array or a promising doctoral student may be found.",
      "<strong>The graduate scheme from hell</strong>",
      "In the old days, espionage recruited polyglots, defectors and lonely men in embassies. The new model, according to the more excitable version of events, recruits high achievers with immaculate transcripts, polished fitness scores and a willingness to move cities or countries for “strategic exposure”. Many, it is said, have passed through formal Defence Force training before being rebadged as analysts, disability support workers, interns, environmental consultants or whatever civilian title sounds least likely to alarm a target. Their preparation allegedly includes cryptography, Mandarin networking etiquette, procurement jargon and the art of looking fascinated during a panel on resilient block chains.",
      "<img class='article-inline-image' src='assets/spies3.PNG'><small class='article-inline-caption'>Spies of the modern era?</small>",
      "Suspected operatives, in this telling, have been sighted in peculiar places: at Chinese university gatherings where the dumplings were better than the questions; in late-night assignations at suburban train station bicycle storage sheds; in the bush, where no one expects to find a junior analyst with polished shoes and concealed satellite communication equipment; and near strange vessel operations whose purpose was explained, unhelpfully, as “aquatic collaboration exercises”.",
      "<strong>Radar, routers and résumés</strong>",
      "Australia’s over-the-horizon radar, that vast and ghostly apparatus for seeing what the eye cannot, makes an ideal object of conspiracy. It is remote, technical and important enough to attract real interest. Add Silicon Valley connections, clandestine meetings with Chinese ‘acquaintances’ in Chicago, a few defence-adjacent start-ups and the evergreen suspicion that every accelerator programme is a cover for something, and the story nearly writes itself. ",
      "The genius of the supposed scheme is not its cloak-and-dagger romance but its bureaucratic plausibility. A spy with a false passport attracts attention. A trainee with a slide presentation or entertaining video attracts coffee. A case officer must hide. A graduate fellow can ask, brightly, whether the group has considered dual-use applications and whether anyone has a spare visitor or vehicle pass.",
      "<strong>The beach installations nobody ordered</strong>",
      "Then there are the sculptures. Along certain beaches, according to the field notes, strange sculptures have appeared at dawn: body parts created in sand, excavations arranged with surveyor’s precision, driftwood tripods pointing out to sea. Footprint evidence suggests multiple booted or barefoot collaborators. Locals call it art, councils call them “temporary cultural activations,” the State call it Aboriginal heritage. The anxious call them signals.",
      "<img class='article-inline-image' src='assets/spy.JPG'><small class='article-inline-caption'> Seemlingly crude beach sculptures. Is the crudeness an intentional distraction?</small>",
      "In the modern security imagination, even public art can look suspicious if viewed through binoculars from a car park at 4am.",
      "<strong>The world’s brightest, put to dim use</strong>",
      "If such a network existed, it would be a monument to the age: youthful, credentialled, mobile, data-hungry and fluent in the language of collaboration. It would not need to steal secrets in the crude sense. It would map people, habits, weak points and ambitions. It would learn who can stand extremes of physical endurance, who is bored in Canberra or Adelaide, who’s up to date with neural network manipulation in California and France, who really wants a job in Italy and who believes every foreign visitor is simply “keen on innovation and learning”.",
      "That is also why the tale is hard to prove and easy to overstate. Open societies are noisy places. Universities host strangers. Trains run late. Boat people do odd things. Bright young people, maddeningly, go where opportunity sends them. Not every coincidence is a cell. Not every networking event is an operation. Yet modern espionage thrives precisely in the gap between paranoia and naivety.",
      "<img class='article-inline-image' src='assets/spies4.jpeg'><small class='article-inline-caption'>The rock cairn; an antiquated messaging spycraft.</small>",
      "<strong>The useful absurdity of suspicion</strong>",
      "The sensible response is neither panic nor shrugging. Governments should protect sensitive research and teach clever people that curiosity is sometimes a cover for collection. Universities should remember that openness is a strength, yet also an opportunity for subversive operatives to expand their networks. Companies should treat improbable approaches with the same caution they apply to improbable money-making opportunities. Families should avoid ‘blind trust’ of their nearest and dearest. ",
      "As for the alleged trainee-spy network, it may be fact, fantasy or that most contemporary of things: a rumour made plausible by the way the world now works. The devious plot, if there is one, is not merely that the youngest and brightest might be used. It is that everyone else has become so used to being networked, profiled and recruited that the operatives can hide in plain sight, wearing a name badge, asking whether there will be certificates (or food) at the end—and quietly adding national security to their LinkedIn skills. ",
      "",
      "<em>Kris Kristensen serves as Chair of the newly-appointed Executive Entity for Defence and Espionage Engagements (EEDEE)."
    ]
  },
  {
    id: "turkey-war",
    featured: false,
    category: "war & conflict",
    title: "The overlooked losers of the Bush Turkey war",
    summary: "Newmarket neighbour condemns Liam's poultry defence strategy",
    author: "Eedee",
    date: "2026-06-28",
    location: "Brisbane",
    readTime: "3 min read",
    image: "assets/bushturkey.png",
    pullQuote: "The campaign harmed neither the turkeys nor their appetite for bananas. Its principal casualty was a neighbouring state.",
    body: [
      "At the Newmarket residence, Liam and his girlfriend faced an increasingly brazen incursion. Bush turkeys were entering the property and eating all the bananas. Conventional diplomacy having failed on account of having no existing communication channels, the household launched its counter offensive with the little resources at hand.",
      "The slingshots were primitive and the campaign remarkably ineffective. Liam’s forces struck their targets with an abysmal accuracy of 5%. Even then, the birds appeared entirely untroubled. They continued their advance as if no opponents existed, continuing to steal the fruit.",
      "Despite failure to repel the turkeys, the nation suffered minimal damage. After all, the bananas, they were expendable.",
      "So the real loser of the Bush Turkey war was neither human nor bird, and emerged long after the conflict was over. A nosy neighbour, apparently monitoring the operations, expressed disapproval of the household’s treatment of the turkeys, despite also acknowledging that the birds were pests by nature.",
      "Analysts believe that the neighbour would be a loser in both outcomes. Live with the pests, or live with attacks on said pests.",
      "The neighbour may also wish to reconsider a new strategic position now they have provided irrefutable evidence of spying next door. The turkeys, meanwhile, remain undefeated, unharmed and presumably well fed."
    ]
  },
  {
    id: "eedee-perspective",
    featured: false,
    category: "perspective",
    title: "Why I bark: policy clarifications",
    summary: "Eedee explains her stance on food security, waste management and public engagement.",
    author: "Eedee",
    date: "2026-06-28",
    location: "Liam's bed",
    readTime: "3 min read",
    image: "assets/eedee-perspective.jpg",
    imageAlt: "Eedee, a brown-and-white dog, looking directly at the camera from a patterned sofa",
    imageCaption: "Video still: Liamconomist",
    video: "assets/dog.mp4",
    videoPoster: "assets/eedee-perspective.jpg",
    videoAlt: "Eedee receiving attention while resting on a patterned sofa",
    videoCaption: "Video: Liamconomist",
    pullQuote: "Remember, I can always bite.",
    body: [
      "I bark because the household requires governance. Governance is a highly complex interconnected system with a narrow margin of error. I bark in order to ensure that the household stays functioning, so everyone has access to food and upholds our right to live in a harmonious environment.",
      "My public facing strategy might seem unusual, callous even. I come up to you, you bend down to pat me, and I leave before you get to. But you see, it is because I can never switch off. Whenever I approach a person, I am not actually asking for pets, instead I'm actually conducting a very thorough inspection. I need to keep my humans safe. But my inspection comes at the cost of braving your rude customs; you weird bipedals think it's okay to bop us on the head. I can tolerate the insult for a while, but as you can see my patience wears thin when every person tries to invade my space. If you really wanted to acknowledge me respectfully, just smell my bum like a normal indiviual.",
      "My food and waste management policies have also attracted criticism. Yeah, I bark at you a lot when you're eating but the reasons are two-fold. One, the risks of under-eating remain steadily high. I must ensure I am adequately satiated. And two, for some reason you are careless with your leftovers. It is unjust, unacceaptable and simply unsustainable to throw away food when I'm right there, under-fed. So my barks are gentle nudges to keep you in check. Sometimes that's not enough, so I have to take matters into my own paws, and that is why I will swipe. It's in the policy, don't act so surprised.",
      "Finally, I would like to shed light on why I bark when you say the W word. If you know my stance, you would know that going for a walk is a social engagement that we don't take lightly. The political implication of mentioning walk but not going for one is similar to, how would I say it for humans to understand, like saying you are a democracy but don't hold elections. The fact that you promise a walk but don't go on one is pure treason, and wreaks havoc upon our just society. Thus a bark is implemented simply to remind you of your sovereign duties.",
      "I wish to thank you all for the opportunity to clarify the intentions behind my barking. Next week I'll elucidate why I growl when I'm happy. Now please give me kibble."
    ]
  },
  {
    id: "familial-generosity",
    featured: false,
    category: "analysis",
    title: "The hidden cost of familial generosity",
    summary: "Exploring the Liam Effect: where fridges tremble in his presence.",
    author: "Caitlyn Cunneen",
    date: "2026-07-04",
    location: "Melboner",
    readTime: "3 min read",
    image: "assets/fridge.png",
    imageCaption: "Image: Liamconomist / Original generated image",
    pullQuote: "Family members have reported a 78% decrease in food disappearance since he got his own fridge in Brunswick.",
    body: [
      "Families are often regarded as the last bastion of unconditional hospitality. A relative arrives at the door, the kettle is put on, the biscuit tin appears, and leftovers mysteriously become 'fair game.' Few illustrate this peculiar economic arrangement better than Liam.",
      "On paper, Liam is a devoted brother, son and uncle. In practice, his visits coincide with a statistically improbable depletion of household food reserves.",
      "Cupboards once stocked with snacks are left noticeably lighter. Cheese vanishes. Leftover curry, carefully saved for tomorrow's lunch, quietly disappears. It has become something of an accepted truth that, wherever Liam goes, the pantry somehow becomes a little less full and the dishes are always done.",
      "The incentives are obvious. Maintaining one's own pantry is expensive; maintaining several others is remarkably economical. By distributing his appetite across an extended family network, Liam has achieved what economists might describe as a highly diversified consumption portfolio. The costs are happily absorbed, while the benefits accrue almost entirely to the diner.",
      "The family, for their part, have adapted. Extra snacks are bought with a knowing smile, leftovers are hidden only half-seriously, and every unexplained disappearance from the fridge is met with the same question: 'Has Liam been here?'. It has become less a source of frustration than a reliable family tradition.",
      "Until meaningful reforms are introduced, such as compulsory snack declarations upon entry or a quota system for leftover consumption, households are unlikely to change their behaviour. After all, a well-fed Liam just another indicator of a successful family gathering.",
      "<em>Caitlyn Cunneen, Liamconomist Correspondent of 25 years, is the world's leading expert on Liam.</em>"
    ],
  },
  {
    id: "water-addiction",
    featured: false,
    category: "analysis",
    title: "What water addiction looks like",
    summary: "The signs can be frightening and misunderstood, until you know what to look for.",
    author: "Anya Suzuki",
    date: "2026-07-04",
    location: "Brisbane",
    readTime: "3 min read",
    image: "assets/water.jpg",
    imageCaption: "Pictured: Liam swimming at Victoria's southern most point.",
    pullQuote: "Where is Liam? Oh in the water again.",
    body: [
      "Friends and family have become increasingly concerned by Liam’s apparent compulsion to enter a body of water upon sight of it. The behaviour cannot reliably be attributed to hygiene, exercise, financial pressure or local custom, and worryingly, in any temperature.",
      "The warning signs first emerged during a camping trip. Faced with the choice between investing in a proper shower costing just $1 and bathing in a freezing lake, Liam launched into the lake. Economists remain divided over whether this represented impressive thrift or a serious collapse in rational decision-making.",
      "The behaviour has not been confined to Australia, pointing to a darker force at play. While hiking in Nepal, Liam encountered an icy river and once again decided that observation was insufficient. His entering the water reportedly alarmed the hiking guide, a professional presumably accustomed to managing altitude, difficult terrain and unpredictable visitors, but not this.",
      "Researchers believe that Liam may experience cold water differently from the general population. Characterised by a loss of control, cravings, and continuous use despite negative consequences, the signs point to addiction.",
      "The pattern is now difficult to dismiss. Freezing lakes, Himalayan rivers and any sufficiently hostile body of water may trigger another episode. Friends are advised to remain calm, carry a towel and avoid pointing out that a warm shower is available nearby."
    ]
  },
  {
    id: "funcle-sandwich",
    featured: false,
    category: "daily briefing",
    title: "The latest technology finally effectively contains Liam",
    summary: "Funcle Sandwich heralded as the innovation of the century.",
    author: "Anya Suzuki",
    date: "2026-07-02",
    location: "Brisbane",
    readTime: "3 min read",
    image: "assets/funcle.jpg",
    imageCaption: "Pictured: Funcle Sandwich technology in action",
    pullQuote: "The baby was truly the linchpin in the breakthrough.",
    body: [
      "After years of failed containment efforts, researchers have unveiled the Funcle Sandwich: a simple but remarkably effective system for keeping Liam in one place.",
      "The technology positions Liam between two family members, creating a layered structure from which escape is socially awkward and physically impractical. An adult applies stabilising pressure from behind while a baby occupies Liam’s arms and attention from the front.",
      "Previous feeble attempts to contain Liam leveraged agentic AI, autonomous vehicles, quantum computing and patesserie skills, blowing past a budget of $2 billion. The Funcle Sandwich succeeds because it converts his responsibilities as a fun uncle into a restraint mechanism.",
      "Early trials produced extraordinary results. Liam remained seated for 68% of the time without beginning an endurance event, entering freezing water or proposing an activity that required everyone to leave the house immediately.",
      "The system is inexpensive, requires no electricity and can be assembled on most sofas. Its principal limitation is the availability of a cooperative baby, though researchers note that Liam appears unusually willing to hold one.",
      "Further testing will determine whether the technology works outdoors. Analysts remain cautious: exposure to a nearby lake, mountain or unattended bicycle may exceed the sandwich’s current containment rating."
    ]
  },
  {
    id: "altitude-sickness",
    featured: false,
    category: "daily briefing",
    title: "Liam hauls 10kg of noodles and coffee up mountain to save $5, immediately gets altitude sickness and can't eat any of it",
    summary: "Is it the smartest or dumbest economic move of the century?",
    author: "Shanan Kilner",
    date: "2026-07-02",
    location: "Nepal",
    readTime: "3 min read",
    image: "assets/altitude-sickness.png",
    imageAlt: "A cut-paper editorial illustration of an exhausted hiker in Nepal carrying an enormous backpack filled with noodles and coffee",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "Water received less attention.",
    body: [
      "Liam’s plan was based on a familiar economic principle: don’t purchase food for an inflated price when you can bring your own.",
      "He therefore packed ten kilograms of two-minute noodles, stale bread from a Nepalese bakery, nuts and coffee, together with a high-altitude gas burner. The intention was to prepare a communal coffee at the summit with his siblings, admire the Nepalese Himalayas and avoid approximately five dollars in meal expenses.",
      "Liam then climbed at a pace better suited to sea level, carrying a substantial quantity of food but barely enough fluid to sustain the person transporting it. In doing so, he conducted an unsupervised experiment into the combined effects of dehydration, exertion and altitude.",
      "The results were conclusive.",
      "By the time Liam reached the summit, he was suffering from altitude sickness and was unable to eat the noodles, enjoy the coffee or properly appreciate the view. The physical achievement of reaching a Himalayan summit was therefore followed by the more modest achievement of sitting beside ten kilograms of uneaten provisions while feeling extremely unwell.",
      "The gas burner was eventually used and the coffee was grudgingly prepared. Liam consumed little of it.",
      "From a narrow accounting perspective, the plan succeeded. Five dollars had been saved. In exchange, Liam forfeited his appetite, his enjoyment of the summit and much of his capacity to remain upright.",
      "The mountain offered a remarkable view and a considerable sense of triumph. Liam experienced neither. The noodles, however, completed the journey in excellent condition.",
      "<em>Shanan Kilner is a Foreign Liamconomist Correspondant. He holds a PhD in Behavourial Liam.</em>"
    ]
  },
  {
    id: "revenge",
    featured: false,
    category: "history",
    title: "Justice served",
    summary: "Loyalty reigns as wheelbarrow found guilty of sister maiming",
    author: "Caitlyn Cunneen",
    date: "2026-06-14",
    location: "Brisbane",
    readTime: "5 min read",
    image: "assets/revenge.png",
    imageAlt: "A cut-paper editorial illustration of a solemn toddler standing over the dismantled remains of a plastic toy wheelbarrow",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "Whoops. That wheely sucks.",
    body: [
      "The conflict began with an incident that, by most adult accounts, would have been classified as a domestic accident. A fall down the stairs ended with Liam's older sister suffering a deep cut to her leg, inflicted by an unfortunate encounter with his plastic toy wheelbarrow. She was taken to hospital for stitches. Liam, two years old and left behind, reached a markedly different conclusion.",
      "For him, there was no ambiguity.",
      "His big sister had been hurt. The wheelbarrow had been there. The guilty party had identified itself. Military historians often search for grand ideological motives behind acts of retaliation. Liam's campaign required no such analysis. It was driven by a simpler doctrine: someone had hurt his sister, and someone had to answer for it.",
      "The accused was, regrettably for itself, still on the premises. While his sister was receiving lifesaving medical care, Liam launched what can only be described as a revenge killing. There would be no investigation into the role of gravity, no consideration of whether the wheelbarrow had acted with intent, and no appeal against the sentence. In Liam's world, justice was neither procedural nor complicated. It was immediate.",
      "The attack was swift and absolute. The wheelbarrow was hunted down and subjected to overwhelming force. Plastic cracked under repeated blows. Its frame was dismantled with the determination of someone avenging a grievous wrong. By the end of the operation, the toy had been reduced to scattered fragments. Reconstruction was neither possible nor contemplated.",
      "By the time his sister returned home, stitched, bandaged and undoubtedly sore, Liam had already delivered what he regarded as justice. The perpetrator had been found and eliminated in her honour. Measured strategically, the operation changed nothing. The stitches remained. The staircase retained its commanding position over household traffic. The laws of physics emerged from the affair entirely unpunished.",
      "Yet to judge the campaign solely by its practical consequences would be to misunderstand its purpose. In Liam's eyes, the world had briefly become divided into two camps: his big sister, and the thing that had made her cry. Faced with that choice, there was never any doubt where his loyalties lay.",
      "The final tally was modest. One injured leg. Several stitches. One plastic wheelbarrow executed without trial. For Liam, however, the campaign was an unequivocal success. His sister had been harmed. He had avenged her.",
      "<em>Caitlyn Cunneen, Liamconomist Correspondent of 25 years, is the world's leading expert on Liam.</em>"
    ]
  },
  {
    id: "handstand-supremacy",
    featured: false,
    category: "opinion",
    title: "When is it okay to do a handstand?",
    summary: "Discrimination against handstands in bars: a symptom of right-way-up supremacy?",
    author: "Ankle Oatmilk",
    date: "2026-06-21",
    location: "Brunswick",
    readTime: "3 min read",
    image: "assets/handstand-supremacy.png",
    imageAlt: "A cut-paper editorial illustration of Liam doing a handstand in a Brunswick bar while rigidly upright patrons look on",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "The right-way-up establishment has mistaken orientation for order.",
    body: [
      "Liam is an avid handstander. Parks, beaches, living rooms and other public spaces are not merely places to stand: they are opportunities to reconsider which limbs should bear the responsibilities of citizenship.",
      "Bars have proved less receptive to this programme. The right-way-up establishment maintains an entrenched expectation that patrons keep their feet near the floor and their heads above it. This convention is presented as common sense, which is how dominant ideologies often avoid having to explain themselves.",
      "The political implications are difficult to ignore. Upright society places the head at the top, the feet at the bottom and calls the arrangement natural. A handstand overturns that hierarchy. Hands—traditionally condemned to labour—suddenly carry the whole system, while the feet enjoy unprecedented social mobility.",
      "Defenders of the existing order cite safety, furniture and the proximity of other people’s drinks. These are not entirely frivolous concerns. A badly timed dismount can turn peaceful inversion into an expansionist foreign policy involving several bar stools.",
      "But a blanket prohibition goes too far. Not every handstand is disorderly, just as not every upright patron is stable. A controlled inversion in an empty patch of floor may pose less danger than a conventionally oriented person after six pints.",
      "A reasonable settlement is possible: no handstands near glassware, crowded walkways or chandeliers, but tolerance wherever space and balance permit. Liam does not seek to abolish standing. He asks only that society recognise another way up.",
    ]
  },
    {
    id: "terraforming-butter",
    featured: false,
    category: "decisions",
    title: "Terraforming butter",
    summary: "CunneenCorp’s trillion-dollar plan to flatten Fridgedœr’s butter mountains has left taxpayers spread thin.",
    author: "Trungo Mumble",
    date: "2026-07-04",
    location: "Fridgedœr",
    readTime: "3 min read",
    image: "assets/terraforming-butter.png",
    imageAlt: "An editorial illustration of construction crews and protesters surrounding two enormous butter mountains inside a frozen refrigerator",
    imageCaption: "Illustration: Liamconomist / Original generated artwork",
    pullQuote: "The cost to the taxpayer is just whey too high.",
    body: [
      "The vast mountain ranges of Bü Teĥr Sœft and Ĺur Pëjk sit in the high alpine, sub-4° country of Fridgedœr. It is here that an unconventional alliance of environmentalists, sandwich artists and dairy enthusiasts have made camp, protesting CunneenCorp's latest venture. ",
      "CunneenCorp, headed by the reclusive entrapaneur Liam Cunneen, has recently filed extraordinary motions within Fridgedœr's national congress to completely flatten both Bü Teĥr Sœft and Ĺur Pëjk. Estimated to cost the country's taxpayers ₩4.2 Billion Western-Stars (approximately $1 Trillion Aud), the company forecasts the project creating thousands of jobs and 'rectifying the problematic terrain.'",
      "A spokesperson for Mr Cunneen spoke exclusively to this paper 'We believe this is the only suitable option for the mountain ranges.' Traversal and harvesting of the range's natural resourses has become untenable and while CunneenCorp has operated at a loss for several years, the undulation and craggyness of these mountains have meant that terraforming has become the only option. ",
      "Mungo Trumble, avid dairy enthusiast, spoke to this reporter on condition of anonymity. 'I don't really understand the fuss, the hills have never affected my harvest. The cost to the taxpayer is just whey too high.'",
      "Congress has referred the plans to its Environmental Cowmission however there are concerns from those opposing the plan that the head of the Cowmission, Furphy 'butterdog' Moon, has been implicated in several high profile corruption investigations, as well as concerns over allegations of jury tampering on a 2022 grand butter larceny trial.  Despite this, Congress and CunneenCorp are confident of a report to be tables in the third quart of the year and a vote by summer, with works to start before the stiff peaks start to melt."
    ]
  },
];
